site_name: MahirKart
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: tr
  font:
    text: Coolvetica
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: red
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: lime
extra_css:
  - src/css/main.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/instagram
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/linkedin
      link: https://github.com/BilalAlpaslan/MahirKart-docs
  