site_name: MahirKart
theme:
  name: material
  features:
    # - navigation.sections
    # - navigation.top
    - navigation.path
    # - navigation.indexes

    # - search.suggest
    # - search.highlight

    # - content.tabs.link
    # - content.code.annotation
    # - content.tooltips
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
  language: tr
  font:
    text: Coolvetica
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: custom 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
extra_css:
  - src/css/main.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/instagram
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/linkedin
      link: https://github.com/BilalAlpaslan/MahirKart-docs
nav:
  - Ana Sayfa: index.md
  - features.md
  # - Pinout: pinout.md
  # - Hızlı Başlangıç: quickstart.md
  - Kullanım Kılavuzu:
    - Python: 
      - userguide/python/quickstart.md
    - Arduino:
      - userguide/arduino/quickstart.md
    - C/C++:
      - userguide/c/quickstart.md  
  # - Hata Ayıklama: troubleshoot.md