site_name: ' '
site_description: MahirKart dökümantasyonuna hoşgeldiniz. MahirKart ile ilgili tüm bilgileri burada bulabilirsiniz. Aviyonik, robotik, IoT, otomasyon ve daha fazlası için kullanabileceğiniz bir geliştirme kartıdır. Roket kurtarma sistemleri, uydu haberleşme kartı, otopilot sistemleri / uçuş kontrol bilgisayarı, yer istasyonu, su altı, su üstü, denge robotları, drone, akıllı ev sistemleri, akıllı fabrika sistemleri, akıllı tarım sistemleri ve daha fazlası
theme:
  name: material
  logo: src\svg\mahirkart logo V1.0.1 badge.svg
  favicon: src\svg\MAHİRKART.svg
  features:
    # - navigation.sections
    # - navigation.top
    - navigation.path
    # - navigation.indexes

    # - search.suggest
    # - search.highlight

    # - content.tabs.link
    # - content.code.annotation
    # - content.tooltips
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
  language: tr
  font:
    text: Coolvetica
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: custom 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
extra_css:
  - src/css/main.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/instagram
      link: https://github.com/BilalAlpaslan/MahirKart-docs
    - icon: fontawesome/brands/linkedin
      link: https://github.com/BilalAlpaslan/MahirKart-docs
  analytics:
    provider: google
    property: G-DEXFWCSC1D
nav:
  - MahirKart: index.md
  - features.md
  - pinout.md
  - quickstart.md
  - Kullanım Kılavuzu:
    - Python: 
      - userguide/python/quickstart.md
    - Arduino:
      - userguide/arduino/quickstart.md
    - C/C++:
      - userguide/c/quickstart.md  
    - Rust:
      - userguide/rust/quickstart.md
    - JavaScipt:
      - userguide/javascript/quickstart.md
  # - Advanced User Guide
  # - Blogs
  - external-resources.md
  # - contributing.md
  # - troubleshoot.md
  # - faq.md
